### ISSUE TITLE
No rule to make target 'xtensa-esp32-elf'

### ISSUE THREAD

**Issue by CyanoFresh** [trombik/toolchain-xtensa32#8]
I've been running vargrant up for 3 hours and it has not compiled yet. Some messages from output:
```
    default: rm -rf libcommon.a
    default: /usr/local/bin/ar rc libcommon.a diagnostic.o diagnostic-color.o diagnostic-show-locus.o diagnostic-format-json.o json.o edit-context.o pretty-print.o intl.o sbitmap.o vec.o input.o version.o hash-table.o ggc-none.o memory-block.o selftest.o selftest-diagnostic.o sort.o
    default: /usr/local/bin/ranlib  libcommon.a
    default: if [ -f ../stage_final ] \
    default:    && cmp -s ../stage_current ../stage_final; then \
    default:   cp ../prev-gcc/cc1-checksum.c cc1-checksum.c; \
    default: else \
    default:   build/genchecksum c/c-lang.o c-family/stub-objc.o attribs.o c/c-errors.o c/c-decl.o c/c-typeck.o c/c-convert.o c/c-aux-info.o c/c-objc-common.o c/c-parser.o c/c-fold.o c/gimple-parser.o c-family/c-common.o c-family/c-cppbuiltin.o c-family/c-dump.o c-family/c-format.o c-family/c-gimplify.o c-family/c-indentation.o c-family/c-lex.o c-family/c-omp.o c-family/c-opts.o c-family/c-pch.o c-family/c-ppoutput.o c-family/c-pragma.o c-family/c-pretty-print.o c-family/c-semantics.o c-family/c-ada-spec.o c-family/c-ubsan.o c-family/known-headers.o c-family/c-attribs.o c-family/c-warn.o c-family/c-spellcheck.o i386-c.o default-c.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a libcommon.a ../libcpp/libcpp.a ../libiberty/libiberty.a   ../libdecnumber/libdecnumber.a ../libbacktrace/.libs/libbacktrace.a \
    default:                      checksum-options > cc1-checksum.c.tmp &&               \
    default:   /usr/ports/lang/gcc9/work/gcc-9.2.0/gcc/../move-if-change cc1-checksum.c.tmp cc1-checksum.c; \
    default: fi
    default: /usr/ports/lang/gcc9/work/.build/./prev-gcc/xg++ -B/usr/ports/lang/gcc9/work/.build/./prev-gcc/ -B/usr/local/x86_64-portbld-freebsd11.1/bin/ -nostdinc++ -B/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/src/.libs -B/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/libsupc++/.libs  -isystem /usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/include/x86_64-portbld-freebsd11.1  -isystem /usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/include  -isystem /usr/ports/lang/gcc9/work/gcc-9.2.0/libstdc++-v3/libsupc++ -L/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/src/.libs -L/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/libsupc++/.libs -fno-PIE -c  -DIN_GCC_FRONTEND -g -O2 -fchecking=1 -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-
    default: virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I/usr/ports/lang/gcc9/work/gcc-9.2.0/gcc -I/usr/ports/lang/gcc9/work/gcc-9.2.0/gcc/. -I/usr/ports/lang/gcc9/work/gcc-9.2.0/gcc/../include -I/usr/ports/lang/gcc9/work/gcc-9.2.0/gcc/../libcpp/include -I/usr/local/include  -I/usr/ports/lang/gcc9/work/gcc-9.2.0/gcc/../libdecnumber -I/usr/ports/lang/gcc9/work/gcc-9.2.0/gcc/../libdecnumber/dpd -I../libdecnumber -I/usr/ports/lang/gcc9/work/gcc-9.2.0/gcc/../libbacktrace  -DLIBICONV_PLUG -o cc1-checksum.o -MT cc1-checksum.o -MMD -MP -MF ./.deps/cc1-checksum.TPo cc1-checksum.c
    default: /usr/ports/lang/gcc9/work/.build/./prev-gcc/xg++ -B/usr/ports/lang/gcc9/work/.build/./prev-gcc/ -B/usr/local/x86_64-portbld-freebsd11.1/bin/ -nostdinc++ -B/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/src/.libs -B/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/libsupc++/.libs  -isystem /usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/include/x86_64-portbld-freebsd11.1  -isystem /usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/include  -isystem /usr/ports/lang/gcc9/work/gcc-9.2.0/libstdc++-v3/libsupc++ -L/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/src/.libs -L/usr/ports/lang/gcc9/work/.build/prev-x86_64-portbld-freebsd11.1/libstdc++-v3/libsupc++/.libs -no-pie   -g -O2 -fchecking=1 -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wn
    default: o-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc  -o cc1 c/c-lang.o c-family/stub-objc.o attribs.o c/c-errors.o c/c-decl.o c/c-typeck.o c/c-convert.o c/c-aux-info.o c/c-objc-common.o c/c-parser.o c/c-fold.o c/gimple-parser.o c-family/c-common.o c-family/c-cppbuiltin.o c-family/c-dump.o c-family/c-format.o c-family/c-gimplify.o c-family/c-indentation.o c-family/c-lex.o c-family/c-omp.o c-family/c-opts.o c-family/c-pch.o c-family/c-ppoutput.o c-family/c-pragma.o c-family/c-pretty-print.o c-family/c-semantics.o c-family/c-ada-spec.o c-family/c-ubsan.o c-family/known-headers.o c-family/c-attribs.o c-family/c-warn.o c-family/c-spellcheck.o i386-c.o default-c.o \
    default:   cc1-checksum.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a   -L/usr/local/lib -lmpc -lmpfr -lgmp   -lz
```

**Comment by CyanoFresh** [comment]
Finally got this at the end:
```
    default: checking for library containing tgetent...
    default: none required
    default: configure: overiding all of --prefix and the likes, because --enable-local was set
    default: configure: creating ./config.status
    default: config.status: creating Makefile
    default: ===>  Building for toolchain-xtensa32-2.50200.80
    default: (cd /usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a && gmake)
    default: gmake[1]: Entering directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default:   SED    'ct-ng'
    default:   SED    'scripts/crosstool-NG.sh'
    default:   SED    'scripts/saveSample.sh'
    default:   SED    'scripts/showTuple.sh'
    default:   GEN    'config/configure.in'
    default:   GEN    'paths.mk'
    default:   GEN    'paths.sh'
    default:   DEP    'nconf.gui.dep'
    default:   DEP    'nconf.dep'
    default:   DEP    'lxdialog/yesno.dep'
    default:   DEP    'lxdialog/util.dep'
    default:   DEP    'lxdialog/textbox.dep'
    default:   DEP    'lxdialog/menubox.dep'
    default:   DEP    'lxdialog/inputbox.dep'
    default:   DEP    'lxdialog/checklist.dep'
    default:   DEP    'mconf.dep'
    default:   DEP    'conf.dep'
    default:   BISON  'zconf.tab.c'
    default:   GPERF  'zconf.hash.c'
    default:   LEX    'zconf.lex.c'
    default:   DEP    'zconf.tab.dep'
    default:   CC     'zconf.tab.o'
    default:   CC     'conf.o'
    default:   LD     'conf'
    default:   CC     'lxdialog/checklist.o'
    default:   CC     'lxdialog/inputbox.o'
    default:   CC     'lxdialog/menubox.o'
    default:   CC     'lxdialog/textbox.o'
    default:   CC     'lxdialog/util.o'
    default:   CC     'lxdialog/yesno.o'
    default:   CC     'mconf.o'
    default:   LD     'mconf'
    default:   CC     'nconf.o'
    default:   CC     'nconf.gui.o'
    default:   LD     'nconf'
    default:   SED    'docs/ct-ng.1'
    default:   GZIP   'docs/ct-ng.1.gz'
    default: gmake[1]: Leaving directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default: (cd /usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a && ./ct-ng -d xtensa-esp32-elf)
    default: GNU Make 4.2.1
    default: Built for amd64-portbld-freebsd11.3
    default: Copyright (C) 1988-2016 Free Software Foundation, Inc.
    default: License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    default: This is free software: you are free to change and redistribute it.
    default: There is NO WARRANTY, to the extent permitted by law.
    default: Reading makefiles...
    default: Reading makefile 'ct-ng'...
    default: gmake[1]: Entering directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk' (search path) (no ~ expansion)...
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk' (search path) (no ~ expansion)...
    default: Shared object "libdl.so.1" not found, required by "bash"
    default: Shared object "libdl.so.1" not found, required by "bash"
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk' (search path) (no ~ expansion)...
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk' (search path) (no ~ expansion)...
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk' (search path) (no ~ expansion)...
    default: Shared object "libdl.so.1" not found, required by "bash"
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk' (search path) (no ~ expansion)...
    default: Updating makefiles....
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:  Considering target file 'ct-ng'.
    default:   Looking for an implicit rule for 'ct-ng'.
    default:   No implicit rule found for 'ct-ng'.
    default:   Finished prerequisites of target file 'ct-ng'.
    default:  No need to remake target 'ct-ng'.
    default: Updating goal targets....
    default: Considering target file 'xtensa-esp32-elf'.
    default:  File 'xtensa-esp32-elf' does not exist.
    default:  Looking for an implicit rule for 'xtensa-esp32-elf'.
    default:  No implicit rule found for 'xtensa-esp32-elf'.
    default:  Finished prerequisites of target file 'xtensa-esp32-elf'.
    default: Must remake target 'xtensa-esp32-elf'.
    default: gmake[1]: *** No rule to make target 'xtensa-esp32-elf'.  Stop.
    default: gmake[1]: Leaving directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default: *** Error code 2
    default:
    default: Stop.
    default: make: stopped in /usr/ports/devel/toolchain-xtensa32
    default: ===>  Building for toolchain-xtensa32-2.50200.80
    default: (cd /usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a && gmake)
    default: gmake[1]: Entering directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default:   GEN    'config/configure.in'
    default:   GEN    'paths.mk'
    default:   GEN    'paths.sh'
    default: gmake[1]: Leaving directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default: (cd /usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a && ./ct-ng -d xtensa-esp32-elf)
    default: GNU Make 4.2.1
    default: Built for amd64-portbld-freebsd11.3
    default: Copyright (C) 1988-2016 Free Software Foundation, Inc.
    default: License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    default: This is free software: you are free to change and redistribute it.
    default: There is NO WARRANTY, to the extent permitted by law.
    default: Reading makefiles...
    default: Reading makefile 'ct-ng'...
    default: gmake[1]: Entering directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk' (search path) (no ~ expansion)...
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk' (search path) (no ~ expansion)...
    default: Shared object "libdl.so.1" not found, required by "bash"
    default: Shared object "libdl.so.1" not found, required by "bash"
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk' (search path) (no ~ expansion)...
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk' (search path) (no ~ expansion)...
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk' (search path) (no ~ expansion)...
    default: Shared object "libdl.so.1" not found, required by "bash"
    default: Reading makefile '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk' (search path) (no ~ expansion)...
    default: Updating makefiles....
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/scripts/scripts.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/samples/samples.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/steps.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/kconfig/kconfig.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/config/config.mk'.
    default:  Considering target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:   Looking for an implicit rule for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:   No implicit rule found for '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:   Finished prerequisites of target file '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:  No need to remake target '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a/paths.mk'.
    default:  Considering target file 'ct-ng'.
    default:   Looking for an implicit rule for 'ct-ng'.
    default:   No implicit rule found for 'ct-ng'.
    default:   Finished prerequisites of target file 'ct-ng'.
    default:  No need to remake target 'ct-ng'.
    default: Updating goal targets....
    default: Considering target file 'xtensa-esp32-elf'.
    default:  File 'xtensa-esp32-elf' does not exist.
    default:  Looking for an implicit rule for 'xtensa-esp32-elf'.
    default:  No implicit rule found for 'xtensa-esp32-elf'.
    default:  Finished prerequisites of target file 'xtensa-esp32-elf'.
    default: Must remake target 'xtensa-esp32-elf'.
    default: gmake[1]: *** No rule to make target 'xtensa-esp32-elf'.  Stop.
    default: gmake[1]: Leaving directory '/usr/ports/devel/toolchain-xtensa32/work/crosstool-NG-6c4433a'
    default: *** Error code 2
    default:
    default: Stop.
    default: make: stopped in /usr/ports/devel/toolchain-xtensa32
    default: find:
    default: /usr/local/share/toolchain-xtensa32: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
